# Form implementation generated from reading ui file '.\screens\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 355)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(210, 50, 101, 20))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(110, 100, 281, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbluser = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lbluser.setObjectName("lbluser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbluser)
        self.lblPass = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblPass.setObjectName("lblPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPass)
        self.txtUser = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtUser.setObjectName("txtUser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUser)
        self.txtPass = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtPass.setObjectName("txtPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPass)
        self.btnLogin = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btnLogin.setObjectName("btnLogin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btnLogin)
        self.btnRegister = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btnRegister.setObjectName("btnRegister")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btnRegister)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ExchangeApp"))
        self.lbluser.setText(_translate("Form", "Usuario"))
        self.lblPass.setText(_translate("Form", "Contraseña"))
        self.btnLogin.setText(_translate("Form", "Ingresar"))
        self.btnRegister.setText(_translate("Form", "Registrarse"))
