# Form implementation generated from reading ui file '.\screens\vender.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 341, 171))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 341, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtMonedaVender = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtMonedaVender.setObjectName("txtMonedaVender")
        self.verticalLayout.addWidget(self.txtMonedaVender)
        self.txtMontoVender = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtMontoVender.setObjectName("txtMontoVender")
        self.verticalLayout.addWidget(self.txtMontoVender)
        self.btnOkCancelVender = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.btnOkCancelVender.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnOkCancelVender.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnOkCancelVender.setObjectName("btnOkCancelVender")
        self.verticalLayout.addWidget(self.btnOkCancelVender)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Vender"))
        self.txtMonedaVender.setText(_translate("Dialog", "Moneda a Vender"))
        self.txtMontoVender.setText(_translate("Dialog", "Monto a convertir "))
