# Form implementation generated from reading ui file '.\screens\comprar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 341, 171))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 341, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtMonedaComprar = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtMonedaComprar.setObjectName("txtMonedaComprar")
        self.verticalLayout.addWidget(self.txtMonedaComprar)
        self.txtMontoComprar = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtMontoComprar.setObjectName("txtMontoComprar")
        self.verticalLayout.addWidget(self.txtMontoComprar)
        self.btnOkCancelComprar = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.btnOkCancelComprar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnOkCancelComprar.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnOkCancelComprar.setObjectName("btnOkCancelComprar")
        self.verticalLayout.addWidget(self.btnOkCancelComprar)

        self.retranslateUi(Dialog)
        self.btnOkCancelComprar.accepted.connect(Dialog.accept) # type: ignore
        self.btnOkCancelComprar.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Compra"))
        self.txtMonedaComprar.setText(_translate("Dialog", "Moneda a comprar"))
        self.txtMontoComprar.setText(_translate("Dialog", "Monto a convertir "))
