# Form implementation generated from reading ui file '.\screens\DepositoDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 331, 161))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 321, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtArs = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtArs.setObjectName("txtArs")
        self.verticalLayout.addWidget(self.txtArs)
        self.btnOkCancelArs = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget)
        self.btnOkCancelArs.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnOkCancelArs.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnOkCancelArs.setObjectName("btnOkCancelArs")
        self.verticalLayout.addWidget(self.btnOkCancelArs)

        self.retranslateUi(Dialog)
        self.btnOkCancelArs.accepted.connect(Dialog.accept) # type: ignore
        self.btnOkCancelArs.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Ingresar ARS"))
        self.txtArs.setText(_translate("Dialog", "Monto en ARS"))
