# Form implementation generated from reading ui file '.\screens\principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(882, 499)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(59, 20, 791, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Welcome = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Welcome.setObjectName("Welcome")
        self.horizontalLayout.addWidget(self.Welcome)
        self.btnLogout = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnLogout.setObjectName("btnLogout")
        self.horizontalLayout.addWidget(self.btnLogout)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 70, 531, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 541, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableSaldos = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget_2)
        self.tableSaldos.setObjectName("tableSaldos")
        self.tableSaldos.setColumnCount(2)
        self.tableSaldos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSaldos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSaldos.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tableSaldos)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 80, 251, 211))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 241, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnIngresarPesos = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnIngresarPesos.setObjectName("btnIngresarPesos")
        self.verticalLayout.addWidget(self.btnIngresarPesos)
        self.btnComprar = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnComprar.setObjectName("btnComprar")
        self.verticalLayout.addWidget(self.btnComprar)
        self.btnVender = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnVender.setObjectName("btnVender")
        self.verticalLayout.addWidget(self.btnVender)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Welcome.setText(_translate("Form", "Bienvenido!"))
        self.btnLogout.setText(_translate("Form", "Cerrar Sesion"))
        self.groupBox_3.setTitle(_translate("Form", "Saldos Disponibles"))
        item = self.tableSaldos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Moneda"))
        item = self.tableSaldos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Saldo Disponible"))
        self.groupBox.setTitle(_translate("Form", "Elija la Opción"))
        self.btnIngresarPesos.setText(_translate("Form", "Ingresar pesos (ARS)"))
        self.btnComprar.setText(_translate("Form", "Comprar moneda extranjera"))
        self.btnVender.setText(_translate("Form", "Vender moneda extranjera"))
