# Form implementation generated from reading ui file '.\screens\registro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 343)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 101, 20))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(110, 60, 331, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbluser = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lbluser.setObjectName("lbluser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbluser)
        self.txtUser = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtUser.setObjectName("txtUser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUser)
        self.lblPass = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblPass.setObjectName("lblPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPass)
        self.txtPass = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtPass.setObjectName("txtPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPass)
        self.lblPass_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblPass_2.setObjectName("lblPass_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPass_2)
        self.txtPass_2 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtPass_2.setObjectName("txtPass_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPass_2)
        self.btnRegister = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btnRegister.setObjectName("btnRegister")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btnRegister)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ExchangeApp"))
        self.lbluser.setText(_translate("MainWindow", "Usuario"))
        self.lblPass.setText(_translate("MainWindow", "Contraseña"))
        self.lblPass_2.setText(_translate("MainWindow", "Repita la Contraseña"))
        self.btnRegister.setText(_translate("MainWindow", "Registrarse"))
